### ISSUE TITLE
IR

### ISSUE THREAD

**Issue by Shaggy013** [warpme/minimyth2#18]
Missing support:
* IR (probably due wrong GPIO declared in DT)

i think not a gpio , it is a pwm 

in quartz64 shematic it is pwm3 

and in some dts files i saw pwm15 pwm7

think you have to search there

**Comment by warpme** [comment]
Argh,
How can i overlooked this?

It is pwm3
(even rockchip tells this...https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/arm64/boot/dts/rockchip/rk3568-pinctrl.dtsi?h=v5.17-rc6#n1802)

So with f18cf59 IR works nicely!

Many thx!
