### ISSUE TITLE
H616 Orange Pi Zero 2 test image

### ISSUE THREAD

**Issue by leeboby** [warpme/minimyth2#24]
Hi, I want to test minimyth2 on Orange Pi Zero 2, Can you sent me a test image, thanks!

**Comment by warpme** [comment]
Hi,

FYI: currently h616 has:
-no audio
-has broken decoded video displaying (issue with sun4i hdmi csc in 5.17 kernel)

Do you till want to test h616?

**Comment by leeboby** [comment]
Yes, I still want it, is decoded video displaying available on Linux5.16 kernel?

**Comment by warpme** [comment]
Here it is: https://github.com/warpme/minimyth2/releases/download/v12.0.0-v33-Pre-193-ge7a9d48089/MiniMyth2-armv8-master-12.0.1.r193-board-h616.orangepi_zero2-SD-Image.img.xz

iirc it was working ok on 5.15.
I was not able to identify where 5.16+ has regression...
