### ISSUE TITLE
Seems wrong md5 checksum of mythtv-32

### ISSUE THREAD

**Issue by andyshrk** [warpme/minimyth2#27]
+++ b/script/myth-32/mythtv/checksums
@@ -1,4 +1,4 @@
-6abbdd34263ddbbfa90eb727606ef335  download/611cac15cc3988e2fbd2305a5662798f2ce8aef0.zip
+5b41de2cff18ecc7d2e6ea1ccb6abd01  download/611cac15cc3988e2fbd2305a5662798f2ce8aef0.zip

this package  md5 checksum seems should be 5b41de2cff18ecc7d2e6ea1ccb6abd01.

I run md5sum against 611cac15cc3988e2fbd2305a5662798f2ce8aef0.zip on ubuntu 20.04 and windows 10, all get this result.

**Comment by warpme** [comment]
Indeed. I found issue being result of interference of git local caching and logic in my automation script which i'm using to automate myth updates.
It is now fixed in 7e60e3e33
Thx for reporting this!
