### ISSUE TITLE
question about hantro ip on rk3566

### ISSUE THREAD

**Issue by amazingfate** [warpme/minimyth2#28]
hello!
I see [this line](https://github.com/warpme/minimyth2/blob/master/html/minimyth/document-changelog.txt#L242) in changelog. Do you mean rk3566 has a hantro g2 video decoder?
As I know there is already [a commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/staging/media/hantro?h=next-20220519&id=5f6bfab6da6531238e899fdf29efd6d0185adc3e) merged into linux-next which says there is a hantro g1 video decoder in rk356x.

**Comment by warpme** [comment]
Ah - this is of course typo!
I was meaning G1.
I'll fix that.
