### ISSUE TITLE
x86 usb stick images don't default to x11

### ISSUE THREAD

**Issue by kjeacle** [warpme/minimyth2#33]
I don't know if this is deliberate or not, but I had to comment out these two lines in /media/boot/minimyth.conf to get the USB stick image to work on my ION2 frontends:

MM_MYTHTV_DRAW_ON='eglfs'
MM_MYTHTV_DRM_VIDEO='yes'

I understand that this might be the default on SoC but perhaps should not be default on x86?

(I think I also had to manually set the theme variables as mentioned in the RPi 4 issue.)

**Comment by warpme** [comment]
Oh indeed!
Good catch. This is bug in introduced in https://github.com/warpme/minimyth2/commit/6627a77864e86bbc509d6d69bf34f587909cef27#diff-59284336fa908d87e216e69e97aff18360b133f1c6bb39032a169b6bd8250967
For sure both lines should be commented as on x86 world, x11 is still best choice. 
I'll fix this!
thx!

**Comment by warpme** [comment]
Karl,
May you pls try:
https://github.com/warpme/minimyth2/releases/download/v12.6.1-v33-Pre-763-g6034adfa56/MiniMyth2-x86-64-master-12.6.1.r763-board-x86pc.bios_efi64-SD-Image.img.xz

**Comment by kjeacle** [comment]
This works out of the box for me. Only change was MM_MASTER_SERVER as it's not the same as my DHCP/TFTP server.
