### ISSUE TITLE
Theme menu no longer "Default"

### ISSUE THREAD

**Issue by kjeacle** [warpme/minimyth2#34]
In v12.6.2-v32, the theme menu is no longer "Default". It is "Media Center Menu Theme". I can go into settings and change it back to "Default" but this does not survive a reboot.

I tried setting MM_THEMEMENU_NAME='Default' but that didn't do anything - not sure if that's the right variable.

**Comment by warpme** [comment]
Oh this is bug.
Should be flxed in v12.6.3...

**Comment by kjeacle** [comment]
Tested working - thanks!
