### ISSUE TITLE
question 4.4.1 5.1.2

### ISSUE THREAD

**Issue by Shaggy013** [warpme/minimyth2#36]
Hey warpme

wich ffmpeg does kodi use for 20 alpha 3

4.4.1-nexus-alpha1 or the 5.1.2-nexus-alpha3 for rockchip ?

**Comment by warpme** [comment]
Im pretty sure it is 4.4.1-nexus-alpha1
in kodi 5.0 is in development (https://github.com/xbmc/xbmc/pull/21248)

**Comment by Shaggy013** [comment]
uhh 

https://github.com/xbmc/FFmpeg/releases/tag/5.1.2-Nexus-Alpha3

**Comment by warpme** [comment]
Shaggy013,
Should I close this ticket?
Or do you expecting something else?

**Comment by Shaggy013** [comment]
Sure you can close

Your always on top of changes so i won't doubt you.

it was just litte weird for me of the alpha3 naming.
