### ISSUE TITLE
H313 board ethernet issue

### ISSUE THREAD

**Issue by kernelgurumeditation** [warpme/minimyth2#54]
Hi, 

first thanks for the project, it's very useful!
I have an INEXT h313 board that uses lddr3, your sdimage h313.x96_q_lpddr3, boots and is stable, but has an issue, the ethernet doesnt work.
So HDMI works, LED works! :D , USB works 

This board doesn't have wifi/Bluetooth so having ethernet working is a must.

I'm adding dmesg and uboot logs and the android device tree in case you have a chance to give it a look.

thanks

[dmesg.txt](https://github.com/warpme/minimyth2/files/13405176/dmesg.txt)
[u-boot.txt](https://github.com/warpme/minimyth2/files/13405177/u-boot.txt)
[android_device_tree.txt](https://github.com/warpme/minimyth2/files/13405241/android_device_tree.txt)

**Comment by warpme** [comment]
Well - I'm afraid without access to real hardware i can't help you...

**Comment by warpme** [comment]
Closed due no hardware to work-on.
