### ISSUE TITLE
rk3528 hdmi audio is ok?

### ISSUE THREAD

**Issue by sputnik2019** [warpme/minimyth2#56]
rk3528 hdmi audio is ok?

**Comment by warpme** [comment]
It think no as i was not able to get hdmi working (yet)
Issue is that this soc has vop3 which has zero support in mainline.
Lack of vop3 holds me with testing my rk3528 dw-hdmi code...so this is kind of chicken-and-egg problem :-(
I have patches for bsp vop3 addition - but last time i was looking on this i conclude i'm too weak in rk vop to add vop3 in mainline....
