### ISSUE TITLE
Installation on X96 X6 Rk3566

### ISSUE THREAD

**Issue by Vanngocan** [warpme/minimyth2#57]
Hi,

Thank you for a very interesting project!

I want to install on my TV box X96 X6 running on Rk3566 with 8GB RAM. Which image I should download?

**Comment by warpme** [comment]
Please use image for x96-x6 tvbox

**Comment by Vanngocan** [comment]
Thank you very much! I have just downloaded the latest image for X96 X6. I will try with my tv box, hope it would work well.

-- 
Best regards,
Van Ngoc An

**Comment by TiBismarthome** [comment]
@warpme please help me file .img for X96 X6 (debian/armbian 11/12). i need use for Home Assistant server. Thks a lot!
