### ISSUE TITLE
are you still pushing your changes to github?

### ISSUE THREAD

**Issue by hexdump0815** [warpme/minimyth2#58]
i was following this repo for quite some time as a good source for patches for various hardware and despite the changelog and images being updated from time to time still, there were no real changes to this repo for a few months now - did you intentionally or non intentionally stop to push your latest code/patches to this github repo?

best wishes - hexdump

**Comment by warpme** [comment]
Hi my friend!

oh - new job, absolutely no time but….

I put also comment on projects pages:

Last years I funded my semi-lab with 15+ various TVboxes by my private money and decided to stop investing my private money - effectively just (and seems only) - to increase sells of tv box vendors.
If you want me to work on various issues or add new hardware support - pls consider donation to help me get required hardware to work on. Please note that this will also increase my satisfaction from - currently free of charge - work on minimyth2/miniarch.

**Comment by hexdump0815** [comment]
as often as you seem to update your changelogs and minimyth builds i doubt that time is the real reason for no longer pushing your updates ... in theory i think you are actually supposed to keep the updated sources somewhere available if you publish newer minimyth images to be in sync with the gpl license of the linux kernel and other used software packages ... also imagine what would happen to your project if other projects like mesa or the linux kernel would stop updating the sources they use? i think one of the nice and good aspects of open source is sharing and collaborating ...

**Comment by warpme** [comment]
Oh well...lack of sufficient time is reason why i stopped (for the moment) to expose my work to others. I started massive rework of build system. I'm in the middle but it looks effort is bigger than i initially estimated. To be loyal to my users i still providing binaries - but sources are actually not in shape i want to publish. Your argument with gpl is understandable...but nature of this discussion resulted (currently) with lost motivation to freely share my work to others. You know: using law argument to push somebody to share his work for free is not my world. Now - I want to end this discussion. All best for you!
